---
title: "Avaliação de modelos de *deep-learning* para detecção de embarcações em áreas marinhas protegidas a partir de imagens ópticas de satélite"
author: "Rodrigo Sant'Ana & Letícia Zorzi Rama"
date: today
lang: pt-BR

format:
  pdf:
    documentclass: article

    classoption:
      - 12pt
      - a4paper
      - openany
    geometry:
      - top=3cm
      - bottom=2.5cm
      - left=2.5cm
      - right=2.5cm
      - headheight=32pt
      - headsep=20pt
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    citecolor: blue
    
    include-in-header:
      - header.tex

bibliography: referencias.bib
csl: frontiers-in-marine-science.csl      

execute:
  echo: false
  warning: false
  message: false
---

# Contextualização

\noindent A inteligência artificial vem sendo progressivamente incorporada na detecção de embarcações de pesca em Áreas Marinhas Protegidas [@welch2024_global_fishing_ai]. Isso se evidencia na proliferação de modelos de visão computacional desenvolvidos com algoritmos de aprendizado profundo para a detecção de objetos com imagens ópticas de satélite [@wang2025_oriented_detection]. Com múltiplas camadas, tais algoritmos aprendem diretamente dos dados, tornando-se eficazes no reconhecimento de padrões complexos [@lecun2015_deep_learning; @goodfellow2016_deep_learning; @glassner2021_deep_learning_visual; @zhang2023_dive_deep_learning]. Por isso, ao aprendizado profundo se atribuem avanços na resolução de problemas desafiadores, incluindo os de visão computacional [@szeliski2022_computer_vision].

Esses avanços se refletem diretamente no sensoriamento remoto, um campo fértil para a visão computacional [@savelonas2022_remote_sensing_review]. Entre as tarefas, destaca-se a detecção orientada de objetos, sendo embarcações uma categoria recorrentemente explorada na literatura científica [@zhao2024_ship_detection_advances] e o monitoramento da pesca uma das motivações [@liang2025_ship_detection_dl]. Por isso, inovações advindas dessa interseção entre aprendizado profundo, visão computacional e sensoriamento remoto vêm sendo incorporadas nos mecanismos internacionais de gestão pesqueira e conservação da biodiversidade marinha conhecidos como Áreas Marinhas Protegidas [@gerhardinger2011_mpa_dramas] as quais já fazem uso histórico do sensoriamento remoto [@kachelriess2014_remote_sensing_mpa].
Em 2018, o Brasil decretou como Áreas Marinhas Protegidas tanto o arquipélago de São Pedro e São Paulo quanto as ilhas da Trindade e o arquipélago Martin-Vaz [@soares2018_remote_mpa]. Este mosaico, conhecido como Grandes Unidades Oceânicas (Souza Junior, 2021), registra a pesca ilegal, não regulamentada e não reportada (IUU) [@pinheiro2018_vitoria_trindade; @francini2018_spsp], um dos desafios globais na gestão dessas áreas [@iacarella2021_noncompliance; @grey2023_vessel_classification]. Como mecanismo de gestão, realizam-se operações de fiscalização, monitoramento e controle com dados de posicionamento, baseadas em sistemas que ainda permitem pontos cegos. Cenários assim incitam soluções com inteligência artificial, capazes de integrar dados de sensoriamento remoto em sistemas mais transparentes para a detecção de embarcações de pesca a partir de imagens ópticas de satélite [@welch2024_global_fishing_ai].

# Objetivos

## Objetivo Geral

Avaliar a performance de modelos de aprendizado profundo para a detecção orientada de embarcações de pesca em Áreas Marinhas Protegidas, a partir de imagens ópticas de satélites.

## Objetivos Específicos

a) Compilar uma base de dados para treinamento e teste dos algoritmos; 
b) Propor um pipeline para implementação e avaliação dos algoritmos; 
c) Avaliar algoritmos de aprendizado profundo para detectar embarcações de pesca a partir de imagens de ópticas satélite de diferentes resoluções e sensores; 
d) Consolidar uma ferramenta iterativa para avaliação dos resultados, além de sua divulgação à comunidade em geral.

# Abordagem Metodológica Proposta

## Fonte de dados

\noindent Como fonte inicial de informações serão compilados dados (e.g. imagens de satélite) de fontes publicas, tais como: 

- Google Earth Engine; 
- Google Earth Pro.  

\noindent Adicionalmente, será buscado aquisitar imagens de satélite a partir de empresas dedicadas ao fornecimento deste tipo de serviço. Por exemplo, Vantor, Planet, Airbus, entre outras. 

Como forma de explorar sinergias, o primeiro foco de contato está sendo com a Airbus, pois a Vantor já está sendo contatada pela Profa. Marie Ruffener da UFRN. Adicionalmente, será buscado contato novamente com a Planet, como forma de exaurir potenciais coberturas de dados satelitais. 

Ainda neste sentido, como forma de ampliar as bases que serão utilizadas para treino do algoritmo, duas estratégias adicionais serão buscadas:

- Utilizar parte ou uma mixagem das bases de dados compiladas e derivadas do levantamento sistemático da literatura;
- Coletar dados a partir de sobrevoo com drone na área portuária do complexo de empresas pesqueiras de Itajaí e Navegantes.

## Compilação de dados a partir das fontes abertas

\noindent Para a compilação de dados a partir das fontes abertas (e.g. Google Earth Engine e Google Earth Pro) a abordagem de coleta será definida da seguinte forma:

a) Identificação de portos pesqueiros marinhos do Brasil a partir de fontes secundárias como MPA, MMA, GFW, LEMA;
b) Busca por identificação destes portos a partir das bases de imagens satelitais gratuítas;
c) Exportação das imagens com a melhor resolução possível a partir da identificação de embarcações nas seções observadas dos mesmos. E, neste sentido, para reduzir da melhor forma possível a subjetividade do processo, as etapas abaixo devem ser seguidas:  
    c.1) A coleta das imagens deverá ser realizada sempre pelo(a) mesmo(a) especialista. Reduzindo assim o viés de amostrador;  
    c.2) Os meta-dados devem ser armazenados em banco de dados textual, dentre as informações coletadas devem estar, sempre que possível, a data da coleta, a data da imagem, o município da imagem, a UF da imagem, a altitude referente a zoom definido no momento da exportação, a classificação da imagem (Oceano | Porto | Misto), o nome do arquivo da imagem, a fonte dos dados;  
    c.3) Para definição do máximo zoom, o(a) especialista deve definir o momento ligeiramente anterior a extrapolação do pixel;  
d) Adicionalmente, para melhor detecção de zonas no Oceano aberto onde ocorrem as atividades de pesca de interesse do projeto informações do GFW e/ou PMAP-SC serão utilizadas como forma a definir áreas e épocas de busca.

## Compilação de dados a partir de fontes pagas

\noindent Por se tratar de um custo relativamente alto, as compras de imagens deverão ser mais certeiras, a proposta é aquisitar imagens da zona costeira, portos e adjacências, visando assim maximizar as fontes de informações disponíveis para treino dos modelos. Adicionalmente, busca-se maximizar a sinergia entre projetos CI-BNA e CNPq.

Para melhor estruturar a rotina de coleta de dados a partir destas fontes, para os ambientes oceânicos serão utilizadas informações base que permitam a identificação de áreas e épocas em que as atividades de pesca ocorrem. Para isto serão utilizados dados do GFW. 

A partir destas informações, deverá ser buscada imagens que compatibilizem-se com os locais e épocas identificados como zonas de frequência de observação de embarcações operando. Com isto, será possível determinar quais embarcações, petrechos, épocas e áreas estão sendo utilizadas. Potencializando, não somente a identificação de imagens que apresentem atividades de pesca, como também, possíveis implementações de validações cruzadas para aferição da qualidade dos modelos desenvolvidos. 

# Análise Exploratória de Dados

## Áreas e épocas das atividades de pesca de interesse 
\noindent Compilar uma base de dados para treinamento e teste dos algoritmos (objetivo específico (a)) é um objetivo que irá se decompor em atividades hierarquicamente estruturadas. Uma das atividades será a análise explotarória de dados para se definir áreas e épocas de busca das imagens de satélite. Áreas e épocas de busca são necessárias para maximizar a chance de se encontrar imagens ópticas de satélite, de alta resolução, com embarcações pesqueiras presentes em zonas do Oceano aberto onde ocorrem as atividades de pesca de interesse do projeto. 

Para que áreas e épocas de busca sejam definidas, será preciso descobrir padrões históricos de ocorrência de embarcações de pesca cujas operações incluem áreas no entorno das Grandes Unidades Oceânicas. A descoberta de padrões de ocorrência implicará na coleta de dados históricos de fontes como o GFW e o PMAP-SC. Durante a coleta será necessário conhecer os dados disponibilizados pelo GFW e pelo PMAP-SC no sentido de quais são e o que representam no âmbito da ciência pesqueira. A estrutura abaixo representa essa hierarquia:

|_Compilar uma base de dados para treinamento dos algoritmos;

|__Encontrar imagens de satélite, de alta resolução, com embarcações pesqueiras presentes em zonas do Oceano aberto onde ocorrem as atividades de pesca de interesse;

|___Definir áreas e épocas de busca;

|____Descobrir padrões históricos de ocorrência de embarcações de pesca cujas operações incluem áreas no entorno das Grandes Unidades Oceânicas;

|_____Analisar exploratória dos dados;

|______Coletar dados do GFW e do PMAP-SC;

|_______Conhecer os dados disponibilizados pelo GFW e pelo PMAP-SC no sentido de quais são e o que representam no âmbito da ciência pesqueira.

# Desenvolvimento dos Modelos

A definir...

# Referências